input {
  beats {
    port => 5044
  }
}

filter {
  if "nginx" in [log][file][path] {
    grok {
      match => { "message" => "%{IPORHOST:clientip} - %{DATA:remote_user} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{DATA:request} HTTP/%{NUMBER:httpversion}\" %{NUMBER:response} %{NUMBER:bytes} \"%{DATA:referrer}\" \"%{DATA:agent}\"" }
    }
  }
}

output {
  if "ssh_logs" in [log][file][path] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ssh-logs-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
  }
}