input {
  beats {
    port => 5044
  }
}

filter {
  # Grok para logs típicos de Nginx access.log
  
  filter {
    if [log][file][path] =~ "access" {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
    }
  }

  # Convertir timestamp de Nginx a @timestamp de Elasticsearch
  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
    timezone => "UTC"
  }

  # Convertir status y bytes a enteros
  mutate {
    convert => { "status" => "integer" }
    convert => { "bytes" => "integer" }
  }

  # Opcional: añadir campo de índice para Kibana
  mutate {
    add_field => { "[@metadata][target_index]" => "nginx-logs-%{+YYYY.MM.dd}" }
  }
}

output {
  # Consola para debug durante pruebas
  stdout { codec => rubydebug }

  # Enviar a Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}